import { Archive, ArchiveRestore } from "lucide-react";
import { toggleCategoryArchive } from "@/app/admin/(protected)/catalogue-actions";
import { AdminCategoryEditForm } from "@/components/admin/admin-category-edit-form";
import { AdminCategoryManager } from "@/components/admin/admin-category-manager";
import { getAdminCategories } from "@/lib/admin/catalogue";

export default async function AdminCategoriesPage() {
  const categories = await getAdminCategories();
  return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><p className="text-kicker">Catalogue</p><h1 className="font-display mt-2 text-5xl font-bold">Categories</h1><p className="mt-3 max-w-2xl text-[var(--muted)]">Shape how students discover the catalogue. Categories with active products stay protected from archiving.</p><section className="surface-card mt-8 p-5 sm:p-7"><h2 className="font-display text-3xl font-bold">Add a category</h2><AdminCategoryManager /></section><section className="surface-card mt-8 overflow-hidden">{categories.length ? categories.map((category) => <article className="border-b border-[var(--line)] p-5 last:border-0" key={category.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-black">{category.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">/{category.slug} · {category.productCount} product{category.productCount === 1 ? "" : "s"}{category.archived ? " · Archived" : ""}</p>{category.description ? <p className="mt-3 max-w-xl text-sm text-[var(--muted)]">{category.description}</p> : null}</div><div className="flex flex-wrap gap-2"><AdminCategoryEditForm category={category} /><form action={toggleCategoryArchive.bind(null, category.id, !category.archived)}><button className="button-secondary focus-ring" type="submit" disabled={!category.archived && category.productCount > 0} title={!category.archived && category.productCount > 0 ? "Archive or move its products first" : undefined}>{category.archived ? <ArchiveRestore size={16} /> : <Archive size={16} />}{category.archived ? "Restore" : "Archive"}</button></form></div></div></article>) : <p className="p-8 text-[var(--muted)]">No categories yet. Create one above.</p>}</section></section>;
}
